version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: ciclo-usr
      MYSQL_PASSWORD: ciclo-usr_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
